//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TipoPiloto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TipoPiloto()
        {
            this.tbl_CiudadOrigenDestino = new HashSet<tbl_CiudadOrigenDestino>();
            this.tbl_Piloto = new HashSet<tbl_Piloto>();
        }
    
        public int id_TipoPiloto { get; set; }
        public string tipoPiloto { get; set; }
        public decimal salarioHora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CiudadOrigenDestino> tbl_CiudadOrigenDestino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Piloto> tbl_Piloto { get; set; }
    }
}
