//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vuelo
    {
        public int id_Vuelo { get; set; }
        public int id_CiudadOrigen { get; set; }
        public int id_CiudadDestino { get; set; }
        public int id_Piloto { get; set; }
        public int cantidadHoras { get; set; }
        public decimal montoSalarioPiloto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual tbl_Ciudad tbl_Ciudad { get; set; }
        public virtual tbl_Ciudad tbl_Ciudad1 { get; set; }
    }
}
