//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VuelosEntitiesConnection : DbContext
    {
        public VuelosEntitiesConnection()
            : base("name=VuelosEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Ciudad> tbl_Ciudad { get; set; }
        public virtual DbSet<tbl_CiudadOrigenDestino> tbl_CiudadOrigenDestino { get; set; }
        public virtual DbSet<tbl_Piloto> tbl_Piloto { get; set; }
        public virtual DbSet<tbl_TipoPiloto> tbl_TipoPiloto { get; set; }
        public virtual DbSet<tbl_Vuelo> tbl_Vuelo { get; set; }
        public virtual DbSet<VW_CIUDAD_DESTINO> VW_CIUDAD_DESTINO { get; set; }
        public virtual DbSet<VW_CIUDAD_ORIGEN> VW_CIUDAD_ORIGEN { get; set; }
        public virtual DbSet<VW_PILOTO> VW_PILOTO { get; set; }
        public virtual DbSet<VW_PILOTO_ORIGEN_DESTINO> VW_PILOTO_ORIGEN_DESTINO { get; set; }
        public virtual DbSet<VW_VUELO> VW_VUELO { get; set; }
    
        public virtual ObjectResult<sp_Ciudad_Destino_Retorna_Result> sp_Ciudad_Destino_Retorna(Nullable<int> id_Ciudad_Origen)
        {
            var id_Ciudad_OrigenParameter = id_Ciudad_Origen.HasValue ?
                new ObjectParameter("id_Ciudad_Origen", id_Ciudad_Origen) :
                new ObjectParameter("id_Ciudad_Origen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Ciudad_Destino_Retorna_Result>("sp_Ciudad_Destino_Retorna", id_Ciudad_OrigenParameter);
        }
    
        public virtual ObjectResult<sp_Ciudad_Origen_Retorna_Result> sp_Ciudad_Origen_Retorna()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Ciudad_Origen_Retorna_Result>("sp_Ciudad_Origen_Retorna");
        }
    
        public virtual ObjectResult<sp_Origen_Destino_Duracion_Retorna_Result> sp_Origen_Destino_Duracion_Retorna(Nullable<int> id_CiudadOrigen, Nullable<int> id_CiudadDestino)
        {
            var id_CiudadOrigenParameter = id_CiudadOrigen.HasValue ?
                new ObjectParameter("id_CiudadOrigen", id_CiudadOrigen) :
                new ObjectParameter("id_CiudadOrigen", typeof(int));
    
            var id_CiudadDestinoParameter = id_CiudadDestino.HasValue ?
                new ObjectParameter("id_CiudadDestino", id_CiudadDestino) :
                new ObjectParameter("id_CiudadDestino", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Origen_Destino_Duracion_Retorna_Result>("sp_Origen_Destino_Duracion_Retorna", id_CiudadOrigenParameter, id_CiudadDestinoParameter);
        }
    
        public virtual ObjectResult<sp_Piloto_Origen_Destino_Retorna_Result> sp_Piloto_Origen_Destino_Retorna(Nullable<int> id_CiudadOrigen, Nullable<int> id_CiudadDestino)
        {
            var id_CiudadOrigenParameter = id_CiudadOrigen.HasValue ?
                new ObjectParameter("id_CiudadOrigen", id_CiudadOrigen) :
                new ObjectParameter("id_CiudadOrigen", typeof(int));
    
            var id_CiudadDestinoParameter = id_CiudadDestino.HasValue ?
                new ObjectParameter("id_CiudadDestino", id_CiudadDestino) :
                new ObjectParameter("id_CiudadDestino", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Piloto_Origen_Destino_Retorna_Result>("sp_Piloto_Origen_Destino_Retorna", id_CiudadOrigenParameter, id_CiudadDestinoParameter);
        }
    
        public virtual ObjectResult<sp_Piloto_Retorna_ID_Result> sp_Piloto_Retorna_ID(Nullable<int> id_Piloto)
        {
            var id_PilotoParameter = id_Piloto.HasValue ?
                new ObjectParameter("id_Piloto", id_Piloto) :
                new ObjectParameter("id_Piloto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Piloto_Retorna_ID_Result>("sp_Piloto_Retorna_ID", id_PilotoParameter);
        }
    
        public virtual ObjectResult<sp_Piloto_Retorna_PorTipoPiloto_Result> sp_Piloto_Retorna_PorTipoPiloto(Nullable<int> id_TipoPiloto)
        {
            var id_TipoPilotoParameter = id_TipoPiloto.HasValue ?
                new ObjectParameter("id_TipoPiloto", id_TipoPiloto) :
                new ObjectParameter("id_TipoPiloto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Piloto_Retorna_PorTipoPiloto_Result>("sp_Piloto_Retorna_PorTipoPiloto", id_TipoPilotoParameter);
        }
    
        public virtual ObjectResult<sp_Tipo_Piloto_Retorna_Result> sp_Tipo_Piloto_Retorna()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tipo_Piloto_Retorna_Result>("sp_Tipo_Piloto_Retorna");
        }
    
        public virtual int sp_Vuelo_Inserta(Nullable<int> id_CiudadOrigen, Nullable<int> id_CiudadDestino, Nullable<int> id_Piloto, Nullable<int> cantidadHoras, Nullable<decimal> montoSalarioPiloto, Nullable<System.DateTime> fecha)
        {
            var id_CiudadOrigenParameter = id_CiudadOrigen.HasValue ?
                new ObjectParameter("id_CiudadOrigen", id_CiudadOrigen) :
                new ObjectParameter("id_CiudadOrigen", typeof(int));
    
            var id_CiudadDestinoParameter = id_CiudadDestino.HasValue ?
                new ObjectParameter("id_CiudadDestino", id_CiudadDestino) :
                new ObjectParameter("id_CiudadDestino", typeof(int));
    
            var id_PilotoParameter = id_Piloto.HasValue ?
                new ObjectParameter("id_Piloto", id_Piloto) :
                new ObjectParameter("id_Piloto", typeof(int));
    
            var cantidadHorasParameter = cantidadHoras.HasValue ?
                new ObjectParameter("cantidadHoras", cantidadHoras) :
                new ObjectParameter("cantidadHoras", typeof(int));
    
            var montoSalarioPilotoParameter = montoSalarioPiloto.HasValue ?
                new ObjectParameter("montoSalarioPiloto", montoSalarioPiloto) :
                new ObjectParameter("montoSalarioPiloto", typeof(decimal));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Vuelo_Inserta", id_CiudadOrigenParameter, id_CiudadDestinoParameter, id_PilotoParameter, cantidadHorasParameter, montoSalarioPilotoParameter, fechaParameter);
        }
    
        public virtual ObjectResult<sp_Vuelo_Retorna_Result> sp_Vuelo_Retorna()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Vuelo_Retorna_Result>("sp_Vuelo_Retorna");
        }
    }
}
