//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CIUDAD_ORIGEN
    {
        public int id_Ciudad { get; set; }
        public string Ciudad { get; set; }
        public int id_TipoPiloto { get; set; }
    }
}
