//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VUELO
    {
        public int id_Vuelo { get; set; }
        public int id_CiudadOrigen { get; set; }
        public int id_Piloto { get; set; }
        public decimal montoSalarioPiloto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombreCompleto { get; set; }
        public string codigo { get; set; }
        public int cantidadHoras { get; set; }
        public string CiudadOrigen { get; set; }
        public int id_CiudadDestino { get; set; }
        public string CiudadDestino { get; set; }
        public int id_TipoPiloto { get; set; }
        public string tipoPiloto { get; set; }
        public decimal salarioHora { get; set; }
    }
}
